# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='Editor',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='editor',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='News.Category'),
            preserve_default=False,
        ),
    ]
