# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20160530_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
