# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News.Menu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News.Editor'),
        ),
    ]
