# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
