# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HelloBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message=b'\xe6\xa0\xbc\xe5\xbc\x8f\xe9\x8c\xaf\xe8\xaa\xa4', regex=b'^09\\d{2}-?\\d{3}-?\\d{3}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
